apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
  labels: { app: web }
spec:
  replicas: 2
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: broken-image
  namespace: default
  labels: { app: demo-broken }
spec:
  containers:
    - name: app
      image: nginx:this-tag-does-not-exist-9999
